# Generated by Django 5.0.9 on 2026-08-27 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('profile_view', 'Profile view'), ('campaign_view', 'Campaign view'), ('application_submitted', 'Application submitted')], db_index=True, max_length=32)),
                ('target_content_type', models.CharField(blank=True, help_text="e.g. 'campaign', 'creator'.", max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'target_content_type', 'target_id'], name='analytics_e_event_t_d412af_idx')],
            },
        ),
    ]
