# Generated by Django 5.0.9 on 2026-08-27 07:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('twitter_x', 'X (Twitter)'), ('twitch', 'Twitch'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('other', 'Other')], max_length=20)),
                ('budget_min', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('budget_max', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('requirements', models.TextField(blank=True, help_text='Deliverables, content guidelines, brand restrictions.')),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='brands.brand')),
                ('categories', models.ManyToManyField(blank=True, related_name='campaigns', to='creators.category')),
            ],
            options={
                'db_table': 'campaigns_campaign',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='campaign_media/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'campaigns_campaign_media',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'platform'], name='campaigns_c_status_bb9aeb_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['deadline'], name='campaigns_c_deadlin_5d0a38_idx'),
        ),
    ]
