# Generated by Django 5.0.9 on 2026-08-27 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='When creator work is expected to begin (part of the campaign timeline).', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='deadline',
            field=models.DateTimeField(help_text='Final deadline for deliverables (end of the campaign timeline).'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='requirements',
            field=models.TextField(blank=True, help_text='General content guidelines and brand restrictions.'),
        ),
        migrations.CreateModel(
            name='CampaignRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('platform', models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('twitter_x', 'X (Twitter)'), ('twitch', 'Twitch'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('other', 'Other')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'campaigns_campaign_requirement',
                'ordering': ['order', 'id'],
            },
        ),
    ]
