# Generated by Django 5.0.9 on 2026-08-27 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'creators_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True, help_text='Whether the creator is open to new campaigns.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='creators', to='creators.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'creators_creator',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='portfolio/%Y/%m/')),
                ('external_url', models.URLField(blank=True)),
                ('platform', models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('twitter_x', 'X (Twitter)'), ('twitch', 'Twitch'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('other', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='creators.creator')),
            ],
            options={
                'db_table': 'creators_portfolio_item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('twitter_x', 'X (Twitter)'), ('twitch', 'Twitch'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('other', 'Other')], max_length=20)),
                ('handle', models.CharField(max_length=150)),
                ('profile_url', models.URLField(blank=True)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='creators.creator')),
            ],
            options={
                'db_table': 'creators_social_account',
                'ordering': ['-followers_count'],
            },
        ),
        migrations.AddIndex(
            model_name='creator',
            index=models.Index(fields=['is_verified', 'is_available'], name='creators_cr_is_veri_4c61ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('creator', 'platform', 'handle')},
        ),
    ]
