# Generated by Django 5.0.9 on 2026-08-27 08:55

import apps.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='creator_covers/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.common.validators.validate_image_size]),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='kind',
            field=models.CharField(choices=[('portfolio', 'Portfolio'), ('media_kit', 'Media Kit')], default='portfolio', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'pdf', 'mp4', 'mov', 'zip', 'doc', 'docx', 'ppt', 'pptx']), apps.common.validators.validate_attachment_size]),
        ),
    ]
