# Generated by Django 5.0.9 on 2026-08-27 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0003_seed_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deliverables', models.JSONField(blank=True, default=list, help_text='List of deliverable strings.')),
                ('turnaround_days', models.PositiveIntegerField(default=5)),
                ('is_popular', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='creators.creator')),
            ],
            options={
                'db_table': 'creators_package',
                'ordering': ['created_at'],
            },
        ),
    ]
