# Generated by Django 5.0.9 on 2026-08-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_attachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Flagged as spam/abuse by a moderator.'),
        ),
    ]
