# Generated by Django 5.0.9 on 2026-08-27 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_verified_alter_user_is_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationstatus',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Verification statuses'},
        ),
    ]
