# Generated by Django 5.0.9 on 2026-08-27 08:55

import apps.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_verificationstatus_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.common.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='verificationstatus',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='verification_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp']), apps.common.validators.validate_document_size]),
        ),
    ]
