# Generated by Django 5.0.9 on 2026-10-02 18:05

from django.db import migrations, models


def grandfather_existing_accounts(apps, schema_editor):
    """Kural getirilmeden ÖNCE var olan hesapları fotoğraf zorunluluğundan muaf tutar.

    Alan ``default=True`` ile eklendiği için bu veri taşıma adımı olmasa, kuralın
    devreye girdiği an mevcut tüm kullanıcılar (fotoğrafı olmayan markalar ve
    creator'lar dahil) iş verme/iş alma dışında kalırdı. Bu fonksiyon yalnızca
    migration anında var olan satırlara dokunur; bu noktadan sonra açılan her
    hesap alanın ``True`` varsayılanını alır, yani yeni kullanıcılar için
    zorunluluk aynen geçerlidir.
    """
    User = apps.get_model("accounts", "User")
    User.objects.update(profile_photo_required=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_backfill_email_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo_required',
            field=models.BooleanField(default=True, help_text='Whether this account must upload a profile photo before using the main features. Pre-existing accounts were grandfathered out when the rule was introduced.'),
        ),
        migrations.RunPython(grandfather_existing_accounts, migrations.RunPython.noop),
    ]
