# Generated by Django 5.0.9 on 2026-10-02 17:29

import apps.payments.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_transaction_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_oid', models.CharField(db_index=True, default=apps.payments.models.generate_merchant_oid, max_length=64, unique=True)),
                ('purpose', models.CharField(choices=[('brand_access', 'Brand directory access'), ('campaign_escrow', 'Campaign escrow funding')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending at provider'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='created', max_length=20)),
                ('provider', models.CharField(max_length=50)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('access_days', models.PositiveIntegerField(default=0)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_payments', to='payments.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_pos_payment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'purpose'], name='payments_po_status_1460f3_idx')],
            },
        ),
    ]
