# Generated by Django 5.0.9 on 2026-08-27 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/%Y/%m/')),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(choices=[('fashion', 'Fashion'), ('beauty', 'Beauty'), ('food_beverage', 'Food & Beverage'), ('tech', 'Technology'), ('fitness', 'Fitness & Health'), ('travel', 'Travel'), ('gaming', 'Gaming'), ('finance', 'Finance'), ('home_living', 'Home & Living'), ('other', 'Other')], db_index=True, default='other', max_length=32)),
                ('company_size', models.CharField(blank=True, choices=[('solo', '1 (Solo)'), ('small', '2-10'), ('medium', '11-50'), ('large', '51-200'), ('enterprise', '200+')], max_length=16)),
                ('description', models.TextField(blank=True)),
                ('headquarters', models.CharField(blank=True, max_length=255)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'brands_brand',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['industry', 'is_verified'], name='brands_bran_industr_668f17_idx')],
            },
        ),
    ]
