# Generated by Django 5.0.9 on 2026-08-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brand_cover_alter_brand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='has_paid_access',
            field=models.BooleanField(default=False, help_text='Creator dizinini görüntüleme erişimi. Ödeme alındıktan sonra admin panelinden manuel olarak işaretlenir.'),
        ),
    ]
