# Generated by Django 5.0.9 on 2026-10-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_brand_has_paid_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='paid_access_until',
            field=models.DateTimeField(blank=True, help_text='Ücretli erişimin bitiş tarihi. Sanal POS ile satın alınan paketlerde doldurulur; BOŞ bırakılması süresiz erişim demektir (admin tarafından manuel açılan hesaplarla geriye dönük uyumluluk).', null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='has_paid_access',
            field=models.BooleanField(default=False, help_text='Creator dizinini görüntüleme erişimi. Admin panelinden manuel olarak ya da sanal POS ödemesi tamamlandığında otomatik işaretlenir.'),
        ),
    ]
